### ISSUE TITLE
Concurrent checkouts lead to incorrect 'num_allocated' stocks

### ISSUE THREAD

**Issue by TWarszawski** [django-oscar/django-oscar#2102] opened 2016-08-17 00:16 UTC
When two customers check out concurrently for the same product, only one of the checkouts is reflected in the num_allocated field.

Steps to reproduce:
1.  Start sandbox, create two customers, create/pick test product.
2.  Both customers add the product to their baskets and perform a checkout concurrently, making sure both customers finish checkout (click the Place Order button) as close to the same time as possible.

We have reproduced this behavior on a single machine, by performing the above steps with one customer in one browser window and another customer in a second browser window.

Expected Result:
The num_allocated for the product is 2.

Actual Result:
The num_allocated for the product is 1.

**Comment by sasha0** [comment] 2016-10-03 21:53
Thanks for the report.

I'll try to re-create with a test.

**Comment by digicase** [comment] 2016-10-04 02:20
There is another issue from last year discussing this #1811

**Comment by sasha0** [comment] 2017-02-20 12:29
Closing as a duplicate of #1811.

**Closed by sasha0** 2017-02-20 12:29 UTC
