### ISSUE TITLE
Product variant picker broken/changed?

### ISSUE THREAD

**Issue by MasterKeits** [django-oscar/django-oscar#3146] opened 2019-08-18 16:18 UTC
There was a drop-down for choosing product variant.
It created form-group
https://i.imgur.com/1UTymT0.png

Right now it displays product variants in rows.
https://i.imgur.com/L73jAnK.png

**Comment by solarissmoke** [comment] 2019-08-19 04:49
Yes, this behaviour was changed in #2616 - variants how have their own product page by default.

**Comment by MasterKeits** [comment] 2019-08-19 08:50
Right now if you choose the product variant it breaks the funcionality.
If you have product selected Home/Clothing/Django T-shirt
but when you select product variant  it goes Home/Django T-shirt
and you cant choose between variants anymore :S
@sasha0

**Comment by MasterKeits** [comment] 2019-08-21 13:59
@solarissmoke @sasha0 Any update on this?

**Comment by solarissmoke** [comment] 2019-08-21 14:21
I'm afraid I don't understand what the issue is that you're facing?

As noted above, the behaviour was changed in Oscar 2 such that each product variant now has its own detail view by default. The parent product provides a list of variants with the link to each variant - this is now the default way to choose between variants.

So for example https://latest.oscarcommerce.com/en-gb/catalogue/django-t-shirt_8/ is the parent, which lists the variants, e.g., https://latest.oscarcommerce.com/en-gb/catalogue/django-t-shirt_10/. This is not the same view as the parent - note that it has different attributes, and can also have a different price.

**Comment by sasha0** [comment] 2020-03-04 09:30
Yeah, I'm not sure what the issue is too and @solarissmoke already explained changed behavior above.

Closing since there were no other replies from the issue submitter for a while.

**Closed by sasha0** 2020-03-04 09:30 UTC

**Comment by AnasGhrab** [comment] 2021-01-24 13:10
I have the same problem as @MasterKeits. I understand from the comments that its the "default" configuration. But how to change it ?

**Comment by solarissmoke** [comment] 2021-01-25 11:05
@AnasGhrab you need to override `oscar/catalogue/detail.html`, and replace the `{% block variants %}` block with:

```
{% block variants %}
     {% include "oscar/catalogue/partials/add_to_basket_form.html" %}
{% endblock %}
```
Which will then show a dropdown of the available variants.
