### ISSUE TITLE
Performance research

### ISSUE THREAD

**Issue by codeinthehole** [django-oscar/django-oscar#477] opened 2013-01-15 08:56 UTC
_Work in progress_

Oscar could do with a thorough review of performance, looking at where caching can be put in place as well as other considerations.

Tasks:
- [ ] document profiling middleware
- [ ] document caching strategies
- [ ] improve performance of demo site
- [ ] analyse logs of demo site
- [ ] investigate statsd

Tools:
- http://www.webpagetest.org/

Related:
- http://www.morethanseven.net/2013/01/13/django-and-rails-presentation-from-qcon/

**Comment by sasha0** [comment] 2017-05-04 07:51
Closing since the issue is not in the relevant state since it was created - demo site was removed, profiling middleware is deprecated and removed in 1.5. 

Current performance issues to be addressed in terms of the #1828.

**Closed by sasha0** 2017-05-04 07:51 UTC
