### ISSUE TITLE
Issue with license of Unidecode dependency

### ISSUE THREAD

**Issue by craigloftus** [django-oscar/django-oscar#2745] opened 2018-06-14 15:10 UTC
A dep conflict we were having with Unidecode led me to a [Wagtail issue](https://github.com/wagtail/wagtail/issues/3311) pointing out that Unidecode is GPLv2+ licensed, a viral license, which is incompatible with Oscar's BSD license.

We're using Unidecode to sanely strip unicode chars in our custom [slugify](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/core/utils.py#L38) function.

Without just dropping the `OSCAR_SLUG_ALLOW_UNICODE` setting and allowing unicode slugs everywhere, the only alternative I can see would be to adopt a solution like Wagtail's `cautious_slugifier` ([wagtail/core/utils.py#L64](https://github.com/wagtail/wagtail/blob/f0eef2fc88043ba627b89125876f1cfe53b7fc51/wagtail/core/utils.py#L64))?

**Comment by solarissmoke** [comment] 2018-06-15 02:46
The [commit](https://github.com/django-oscar/django-oscar/commit/051c9770ebee4ebd5b17eb287ce1459b76deac7f) that introduced this setting was intended to provide backward compatibility for the `allow_unicode` argument added to Django's own slugify function in Django 1.9.

Since we no longer support Django 1.8 I'd say we just replace this whole thing with Django's and pass `OSCAR_SLUG_ALLOW_UNICODE` as the `allow_unicode` argument.

**Comment by craigloftus** [comment] 2018-06-15 07:42
But the problem with Django's slugify with `allow_unicode=False` is that it just strips the unicode characters, potentially resulting in zero length slugs.

```
slugify('你好')
> ''

slugify(unidecode('你好'))
> 'ni-hao'
```

**Comment by solarissmoke** [comment] 2018-06-15 09:09
Hmm okay. In that case I agree that a `cautious_slugifier` is the best alternative.

**Comment by solarissmoke** [comment] 2018-06-20 04:27
Fixed in #2749.

**Closed by solarissmoke** 2018-06-20 04:27 UTC
Labels: ☁ Bug
