### ISSUE TITLE
IntegrityError at /dashboard/vouchers/create/

### ISSUE THREAD

**Issue by Quantra** [django-oscar/django-oscar#3473] opened 2020-08-06 13:35 UTC
### Issue Summary

IntegrityError at /dashboard/vouchers/create/
UNIQUE constraint failed: offer_conditionaloffer.name

It appears when creating a voucher a conditionaloffer is created using the voucher name.  When the voucher is deleted this condtionaloffer is not deleted.  Creating another voucher with the same name causes this IntegrityError as another conditionaloffer is created using the same name, however the name field on conditionaloffer has unique=True set.

### Steps to Reproduce

Visit /dashboard/vouchers/create/
Create a new voucher.
Delete the new voucher.
Create the voucher again with the same name.

### Technical details

* Python version: 3.5.2
* Django version: 2.28
* Oscar version: 2.0.4

Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in _execute
  84.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py" in execute
  383.         return Database.Cursor.execute(self, query, params)

The above exception (UNIQUE constraint failed: offer_conditionaloffer.name) was the direct cause of the following exception:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py" in post
  142.             return self.form_valid(form)

File "/usr/lib/python3.5/contextlib.py" in inner
  30.                 return func(*args, **kwds)

File "/usr/local/lib/python3.5/dist-packages/oscar/apps/dashboard/vouchers/views.py" in form_valid
  120.             exclusive=form.cleaned_data['exclusive'],

File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py" in create
  422.         obj.save(force_insert=True, using=self.db)

File "/usr/local/lib/python3.5/dist-packages/oscar/apps/offer/abstract_models.py" in save
  231.         return super().save(*args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py" in save
  741.                        force_update=force_update, update_fields=update_fields)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py" in save_base
  779.                 force_update, using, update_fields,

File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py" in _save_table
  870.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py" in _do_insert
  908.                                using=using, raw=raw)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py" in _insert
  1186.         return query.get_compiler(using=using).execute_sql(return_id)

File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  1368.                 cursor.execute(sql, params)

File "/usr/local/lib/python3.5/dist-packages/debug_toolbar/panels/sql/tracking.py" in execute
  192.         return self._record(self.cursor.execute, sql, params)

File "/usr/local/lib/python3.5/dist-packages/debug_toolbar/panels/sql/tracking.py" in _record
  126.             return method(sql, params)

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in execute
  99.             return super().execute(sql, params)

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in execute
  67.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in _execute_with_wrappers
  76.         return executor(sql, params, many, context)

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in _execute
  84.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py" in __exit__
  89.                 raise dj_exc_value.with_traceback(traceback) from exc_value

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in _execute
  84.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py" in execute
  383.         return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /dashboard/vouchers/create/
Exception Value: UNIQUE constraint failed: offer_conditionaloffer.name

**Comment by solarissmoke** [comment] 2020-08-06 14:04
Duplicate of #3279, fixed in Oscar 2.1.

**Closed by solarissmoke** 2020-08-06 14:04 UTC
