### ISSUE TITLE
Style classes for message alerts are wrong

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2107] opened 2016-08-19 06:34 UTC
At least in error alert:
![seleccion_220](https://cloud.githubusercontent.com/assets/5034215/17800962/de3cde20-65ac-11e6-83e6-d96bc5aa9c98.png)

Because Oscar use by default `bootstrap 3` we searched in documentation and fix this error:
![seleccion_221](https://cloud.githubusercontent.com/assets/5034215/17800983/f4447e1c-65ac-11e6-9fcd-27951e0224f1.png)
Instead `alert-error` class use `alert-danger` class.

Review this in [documentation](http://getbootstrap.com/components/#alerts):
![seleccion_222](https://cloud.githubusercontent.com/assets/5034215/17801016/1c8f2142-65ad-11e6-8783-79ccaa1e4edb.png)

**Comment by sasha0** [comment] 2016-10-03 21:29
Duplicate of #1895

**Closed by sasha0** 2016-10-03 21:29 UTC
