### ISSUE TITLE
Can't create new "options" attribute from dashboard

### ISSUE THREAD

**Issue by kosc** [django-oscar/django-oscar#2405] opened 2017-06-27 13:26 UTC
Steps to reproduce:

1. Go to dashboard
2. Create new product type with attribute type 'Option'. Can't select any options at this step (how to add them?)
3. Trying to create some product of new type. 
4. Getting an error with traceback like this:
`Internal Server Error: /dashboard/catalogue/products/3/
Traceback (most recent call last):
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/views.py", line 206, in dispatch
    request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/views.py", line 261, in get_context_data
    ctx = super(ProductCreateUpdateView, self).get_context_data(**kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 45, in get_form
    return form_class(**self.get_form_kwargs())
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 264, in __init__
    self.add_attribute_fields(product_class, self.instance.is_parent)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 305, in add_attribute_fields
    field = self.get_attribute_field(attribute)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 316, in get_attribute_field
    return self.FIELD_FACTORIES[attribute.type](attribute)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 192, in _attr_option_field
    queryset=attribute.option_group.options.all())
AttributeError: 'NoneType' object has no attribute 'options'
ERROR:django.request:Internal Server Error: /dashboard/catalogue/products/3/
Traceback (most recent call last):
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/views.py", line 206, in dispatch
    request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 236, in get
    return super(BaseUpdateView, self).get(request, *args, **kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/views.py", line 261, in get_context_data
    ctx = super(ProductCreateUpdateView, self).get_context_data(**kwargs)
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/kosc/.local/lib64/python3.5/site-packages/django/views/generic/edit.py", line 45, in get_form
    return form_class(**self.get_form_kwargs())
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 264, in __init__
    self.add_attribute_fields(product_class, self.instance.is_parent)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 305, in add_attribute_fields
    field = self.get_attribute_field(attribute)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 316, in get_attribute_field
    return self.FIELD_FACTORIES[attribute.type](attribute)
  File "/home/kosc/.local/lib64/python3.5/site-packages/oscar/apps/dashboard/catalogue/forms.py", line 192, in _attr_option_field
    queryset=attribute.option_group.options.all())
AttributeError: 'NoneType' object has no attribute 'options'
`

**Comment by solarissmoke** [comment] 2017-06-28 04:02
Closing as a duplicate of #1823 - this is a known issue, just that we need someone to spend time implementing it in the dashboard.

**Closed by solarissmoke** 2017-06-28 04:02 UTC
