### ISSUE TITLE
setup() should add zip_safe=False parameter in setup.py 

### ISSUE THREAD

**Issue by john-shine** [django-oscar/django-oscar#2685] opened 2018-04-25 09:31 UTC
cd django-oscar folder
python setup.py install
it make django-tables2 install as egg file instead of package folder, then when I enter dashboard, it comes Error:
TemplateDoesNotExist: django_tables2/table.html
take me much time to debug.

To avoid this problem, zip_safe=False parameter should add to setup() in setup.py

**Comment by solarissmoke** [comment] 2018-06-01 04:47
As per my comment in #2695, it looks like this is an issue with dependency packages rather than Oscar. I'm closing for now but feel free to reopen if you can clarify the reason this is necessary and steps to reproduce the problem.

**Closed by solarissmoke** 2018-06-01 04:47 UTC
