### ISSUE TITLE
Sandbox build broken because django-widget-tweaks doesn't get installed

### ISSUE THREAD

**Issue by mbertheau** [django-oscar/django-oscar#1658] opened 2015-02-06 14:20 UTC
To reproduce:
```bash
$ mkvirtualenv oscar
(oscar) $ make sandbox
...
sites/sandbox/manage.py syncdb --noinput
Traceback (most recent call last):
  File "sites/sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/markus/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/markus/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/markus/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/markus/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/markus/.virtualenvs/oscar/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named widget_tweaks
make: *** [build_sandbox] Error 1
```

`django-widget-tweaks` is listed in https://github.com/django-oscar/django-oscar/blob/cd5bb8f741ec68a7f29b3c7379defd56d4774068/setup.py#L70 so it's not immediately obvious to me why make install doesn't install it.

**Comment by maikhoepfel** [comment] 2015-02-06 21:33
Yes, I ran into that and thought it's me because my virtualenv got stale or
something. We did change what make install does; it now uses pip to both
install Oscar dependencies and dev dependencies. I wonder if I
misunderstood how that works.

**Comment by rayrrr** [comment] 2015-02-23 19:32
I think the problem package is simply missing from the requirements.txt files. I had the same problem trying to build the US Site using the current repo, so I went in to the requirements_us.txt file and added the line:

> django-widget-tweaks==1.3

I then re-ran the "make us_site" command and it worked...at least to a point. I think there's some other problems with it too when using `manage.py runserver` (had to manually copy the image_not_found.jpg file into my MEDIA_ROOT and then got a PIL error with the same jpg once it was copied, after creating a fresh virtualenv to work in). At least with this workaround you can build the sandboxes and inspect the structure and contents of the files.

**Comment by maikhoepfel** [comment] 2015-02-26 10:28
@rayrrr Oscar core dependencies should be specified in ``setup.py``. We use ``requirements.txt`` only for Oscar development related requirements. And ``django-tweaks`` is specified in ``setup.py``, so that's why we're surprised to not see it being installed. Any pointers welcome!

**Comment by rayrrr** [comment] 2015-02-26 14:00
@maikhoepfel I think you're confused–otherwise I'm missing something. First of all, we're talking about the `settings.py` file, right? "setup.py" is not a Django convention I know of.

In Django, the `INSTALLED_APPS` entry in `settings.py` is where you specify which Python modules you want your app to use, but it expects those modules to already be available in your virtualenv.

`requirements.txt` is what you use to make the modules available in your virtualenv! You need to specify `django-tweaks

**Comment by rayrrr** [comment] 2015-02-26 14:13
@maikhoepfel upon further inspection of your Makefile, I think what's going on here is that you have one "global" `requirements.txt` for Oscar dev dependencies, and another `requirements_XX.txt` per XX build for the demo, and us site. However, the sandbox has no requirements file of its own.

I was trying to check out the US site, I put the missing mention of django-widget-tweaks in the `requirements_us.txt` file (see my original comment for exact syntax). So @mbertheau for trying out the basic sandbox, you can just add the mention to the "global" `requirements.txt` file.

**Comment by maikhoepfel** [comment] 2015-03-02 13:30
@rayrrr I'm afraid you're missing something. As we're publishing Oscar on PyPi, we're following the [Python packaging guidelines](https://packaging.python.org/en/latest/distributing.html#setup-py). 

I would expect that the requirements specified in ``setup.py`` get installed [here](https://github.com/django-oscar/django-oscar/blob/master/Makefile#L5). And they do, otherwise we e.g. wouldn't have Django in the virtualenv as it's not specified in any ``requirements.txt``.

**Comment by maikhoepfel** [comment] 2015-03-13 11:36
@mbertheau Can you still reproduce this? The sandbox builds fine for me now, with a fresh venv.

**Comment by zuck** [comment] 2015-06-02 04:47
It seems that is still broken, because the online sandbox is definitely not up-to-date with *master branch* (Bootstrap 2.3.1), nor the demo site...

**Comment by sasha0** [comment] 2015-06-10 13:07
@maikhoepfel sandbox builds fine for me too.
@zuck please suggest how to reproduce the issue. Thanks.

**Comment by zuck** [comment] 2015-06-11 02:55
Maybe I was wrong and it isn't strictly related to *django-widget-tweaks* but something wrong is happening with *online* sandbox generation (http://latest.oscarcommerce.com) because it is definitely *not up-to-date* to the latest version (nor the demo).

**Comment by mvantellingen** [comment] 2016-07-13 09:58
Seems to be fixed in the meantime

**Closed by mvantellingen** 2016-07-13 09:58 UTC
Labels: ☁ Bug
