### ISSUE TITLE
Consumer to consumer (C2C) ecommerce

### ISSUE THREAD

**Issue by Hadar11** [django-oscar/django-oscar#3390] opened 2020-06-04 16:51 UTC
Can you please advise if Oscar allows Consumer to consumer (C2C) ecommerce requirements , the reason for my question  https://github.com/django-oscar/django-oscar indicates to Oscar as "... allows a wide range of e-commerce requirements to be handled, from large-scale B2C sites to complex B2B sites rich in domain-specific business logic", also it seems sandbox is not allowing the user to sell their products but just to buy.

**Comment by solarissmoke** [comment] 2020-06-06 04:49
Oscar doesn't currently support the C2C use case out of the box. It would definitely be possible to build such a service on top of Oscar, leveraging all the existing functionality (catalogue, reviews, checkout, payment flows, etc). You would have to add a substantial amount of logic to handle the C2C-specific functionality, which would require getting hands fairly dirty with the internals of Oscar.

Hope that answers your question. I'm closing this issue as this is not a bug/feature request - if you want to discuss this further the mailing list is probably the best place to do that.

**Closed by solarissmoke** 2020-06-06 04:49 UTC

**Comment by Hadar11** [comment] 2020-06-08 05:10
Thanks Samir
