### ISSUE TITLE
ProductAttribute.product_class nullable

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1830] opened 2015-08-24 15:44 UTC
Why would one leave `ProductAttribute.product_class` null? I assume it's for product attributes that aren't specific to one product class, such as shipping dimensions or shipping weight. However, if you don't specify a product class, it doesn't show up in the dashboard, so you can't actually enter those values.

I'm debating whether to modify `apps.dashboard.catalogue.forms.ProductForm.add_attribute_fields` to add those extra fields, or maybe just create similar attributes for each product class. (e.g. tshirt_shipping_weight, sweater_shipping_weight, etc.)

Thoughts?

**Comment by sasha0** [comment] 2015-11-22 00:57
> I'm debating whether to modify apps.dashboard.catalogue.forms.ProductForm.add_attribute_fields to add those extra fields

I think it does make much more sense to allow to edit product attributes, not specific to product.

**Comment by mvantellingen** [comment] 2015-11-22 19:09
Perhaps @codeinthehole  or @maikhoepfel can let us know

**Comment by john-parton** [comment] 2015-11-23 14:36
It's not sufficient just to update the dashboard. `ProductAttributesContainer` might have to be reworked slightly.

I can submit a PR.

**Comment by solarissmoke** [comment] 2017-04-22 06:28
Closing as duplicate of #1633.

**Closed by solarissmoke** 2017-04-22 06:28 UTC
