### ISSUE TITLE
Forms need to be loaded dynamically by ALL views modules

### ISSUE THREAD

**Issue by andirigible** [django-oscar/django-oscar#2750] opened 2018-06-15 19:06 UTC
### Issue Summary

Dashboard flatpages forms are not loaded dynamically into the respective view module, but directly imported. This is also true for the reviews forms.

### Steps to Reproduce

1. Override an existing form in your own `dashboard.pages.forms`
2. Navigate through your dashboard to the view which should show said form
3. Cry?

I'm not really sure why all the other dashboard apps dynamically load forms using `get_class`, and yet `pages` and `reviews` import them directly. This makes it difficult to override those forms, since we now require a view override as well as a form override.

These two view modules _really_ should import their respective forms using `get_class`, unless there's an extremely good reason to favor direct import.

### Technical details

* Python version: 3.6.4
* Django version: 1.11.13
* Oscar version: 1.5.4

### Related issues
#2209 "Needed documentation to ovewrite/modificate dashboard forms"
This issue's primary comment suggests that any dashboard app can be overridden and its forms modified, which is largely, but not completely, true.

**Comment by solarissmoke** [comment] 2018-06-16 03:17
Closing as duplicate of #2595 which was fixed in Oscar 1.6.

**Closed by solarissmoke** 2018-06-16 03:17 UTC
