### ISSUE TITLE
How to use AbstractOption?

### ISSUE THREAD

**Issue by tfeldmann** [django-oscar/django-oscar#2889] opened 2018-11-28 14:45 UTC
At first I want to thank you for this great project. So far it is a joy to use!

I am building a shop where customers should be able customize some properties of the products. I found the `AbstractOption` class in the codebase but I'm stuck - how do I use this? Is this something that can be set in the dashboard and I'm not seeing it? Does this need to be a property of the forked `Product` class? Do I have to assign it to the product in the django shell?

Some nudge in the right direction would be much appreciated!

**Comment by solarissmoke** [comment] 2018-11-29 04:33
The ability to edit `Option`s from the dashboard was just recently added in https://github.com/django-oscar/django-oscar/pull/2829. It will appear in the next release of Oscar (2.0). Until then you have to manage them from the django shell or django admin. 

Hope that helps. Closing as a duplicate of https://github.com/django-oscar/django-oscar/pull/2829.

**Closed by solarissmoke** 2018-11-29 04:33 UTC

**Comment by tfeldmann** [comment] 2018-11-29 09:04
Thank you for the answer. It's working perfectly with the current master branch.
