### ISSUE TITLE
Error when adding a block to page url

### ISSUE THREAD

**Issue by 3ecologias** [django-oscar/django-oscar#2195] opened 2017-01-04 14:20 UTC
I traced this error and tried to fix it on my setup.

apps/dashboard/promotions/forms.py

and edit:
```python
class PagePromotionForm(forms.ModelForm):
...
class Meta:
        model = PagePromotion
        fields = ['position']
```
to instead be:
```python
class Meta:
        model = PagePromotion
        fields = ['position', 'page_url']
```
it did not work.

actually, it is not writing urls into the db, so I had to write it throught django admin

any better solution?

debug bellow:

```python
NoReverseMatch at /dashboard/content-blocks/update/rawhtml/2/
Reverse for 'promotion-list-by-url' with arguments '()' and keyword arguments '{u'path': u''}' not found. 1 pattern(s) tried: [u'dashboard/content-blocks/page/(?P<path>/([\\w-]+(/[\\w-]+)*/)?)$']
Request Method:	GET
Request URL:	http://127.0.0.1:8000/dashboard/content-blocks/update/rawhtml/2/
Django Version:	1.8.17
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'promotion-list-by-url' with arguments '()' and keyword arguments '{u'path': u''}' not found. 1 pattern(s) tried: [u'dashboard/content-blocks/page/(?P<path>/([\\w-]+(/[\\w-]+)*/)?)$']
Exception Location:	/home/tatu/.virtualenvs/recifegrafica/local/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 495
Python Executable:	/home/tatu/.virtualenvs/recifegrafica/bin/python
Python Version:	2.7.10
Python Path:	
['/home/tatu/apps/recifegrafica',
 '/home/tatu/.virtualenvs/recifegrafica/lib/python2.7',
 '/home/tatu/.virtualenvs/recifegrafica/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/tatu/.virtualenvs/recifegrafica/lib/python2.7/lib-tk',
 '/home/tatu/.virtualenvs/recifegrafica/lib/python2.7/lib-old',
 '/home/tatu/.virtualenvs/recifegrafica/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/tatu/.virtualenvs/recifegrafica/local/lib/python2.7/site-packages',
 '/home/tatu/.virtualenvs/recifegrafica/lib/python2.7/site-packages']
Server time:	Qua, 4 Jan 2017 11:18:06 -0300
Error during template rendering

In template /home/tatu/.virtualenvs/recifegrafica/local/lib/python2.7/site-packages/oscar/templates/oscar/dashboard/promotions/form.html, error at line 64
Reverse for 'promotion-list-by-url' with arguments '()' and keyword arguments '{u'path': u''}' not found. 1 pattern(s) tried: [u'dashboard/content-blocks/page/(?P<path>/([\\w-]+(/[\\w-]+)*/)?)$']
54	                <tbody>
55	                    {% for link in links %}
56	                        <tr>
57	                            <td><a href="{{ link.page_url }}">{{ link.page_url }}</a></td>
58	                            <td>{{ link.position }}</td>
59	                            <td>
60	                                <form action="." method="post" >
61	                                    {% csrf_token %}
62	                                    <input type="hidden" name="action" value="remove_from_page" />
63	                                    <input type="hidden" name="pagepromotion_id" value="{{ link.id }}" />
64	
                                          <a href="
      {% url 'dashboard:promotion-list-by-url' path=link.page_url %}
      " class="btn btn-info">{% trans "View all blocks on this page" %}</a>

      
65	                                    <button class="btn btn-default" type="submit" data-loading-text="{% trans 'Removing...' %}">{% trans "Remove from page" %}</button>
66	                                </form>
67	                            </td>
68	                        </tr>
69	                    {% endfor %}
70	                </tbody>
71	            {% else %}
72	                <tr><td>{% trans "This promotion is not displayed anywhere at the moment." %}</td></tr>
73	            {% endif %}
74	        </table>```

**Comment by mvantellingen** [comment] 2017-02-05 11:55
Please re-format the text

**Comment by solarissmoke** [comment] 2017-04-17 05:28
I can't reproduce this. Also, the change you are suggesting (of editing the form class) has no bearing on how the reverse url is generated. Closing as there isn't enough information here to fix this. Please feel free to reopen if you can provide the steps to reproduce the problem!

**Closed by solarissmoke** 2017-04-17 05:28 UTC
Labels: ❓Support question
