### ISSUE TITLE
Why do we need uk and uk_UA?

### ISSUE THREAD

**Issue by dima-kov** [django-oscar/django-oscar#2465] opened 2017-09-28 16:57 UTC
Hello!

Could you, please, explain to me why there are two files for Ukrainian translations: `uk` and `uk_UA`. And the main issue is that there are not all translations in the `uk_UA` file: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/locale/uk_UA/LC_MESSAGES/django.po#L4763

There is not even `uk_UA` language in django settings: https://github.com/django/django/blob/master/django/conf/global_settings.py#L135

So why do we need uk_UA in django-oscar? And, why django chose it, but not `uk` file?

Also, there are files for Russian: `ru` and `ru_RU`. And `ru` is not translated completely but `ru_RU` is.

**Comment by dima-kov** [comment] 2017-10-05 20:53
Any response?

**Comment by okfish** [comment] 2017-10-06 11:32
I guess it's because of Transifex settings or may be for histroric reasons. As of django's source comments
> Language code for this installation. All choices can be found here:
> http://www.i18nguy.com/unicode/language-identifiers.html

follows that we should use two part for lang ID, so uk_UA and ru_RU is correct.
Also, this issue may be an earlier mistake, when messages was generated with incomplete locale names, e.g. `compilemessages -l uk` just places django.po into `locale/uk/LC_MESSAGES/` folder.

**Comment by mmmcorpsvit** [comment] 2017-11-06 13:26
i too understand, but i fix!
1. please download https://www.transifex.com/codeinthehole/django-oscar/oscar/uk/download/for_use/ 
po file, then convert to mo by https://po2mo.net/files/2gose1w
2. replace files in "uk"
3. very important, "uk_UA" delete or rename (i rename to "uk_UA_")

now Ukraine language translate work fine
![9355f60345](https://user-images.githubusercontent.com/9638835/32443205-e112c71e-c306-11e7-9d86-83d2b73d1d60.jpg)

**Comment by mmmcorpsvit** [comment] 2017-11-06 13:28
site-packages\oscar\locale\uk\
[LC_MESSAGES.zip](https://github.com/django-oscar/django-oscar/files/1446333/LC_MESSAGES.zip)

**Comment by sasha0** [comment] 2017-12-17 14:12
Closing as duplicate of #2049.

**Closed by sasha0** 2017-12-17 14:12 UTC
