### ISSUE TITLE
KeyError at /dashboard/catalogue/product-type/create/ u'widget'

### ISSUE THREAD

**Issue by jackgreen04** [django-oscar/django-oscar#2733] opened 2018-06-03 11:24 UTC
### Issue Summary

Hi does any one experience this error specially on oscar 1.6 when your trying to add new product type from the dashboard?

### Steps to Reproduce

Login as a admin in dashboard.
Goto "Catalogue>Product types" then add new.
Then this error will pop up.

This can be consider as a bug because I am using oscar 1.5.4 without this issue then by upgrading to 1.6 this shows up.

**Comment by solarissmoke** [comment] 2018-06-04 04:08
I'm not able to reproduce this - please provide a full stack trace, and also let us know which versions of Python and Django you are using.

**Comment by jackgreen04** [comment] 2018-06-04 08:21
Hello good day thank you for the response, but I think the problem is on the django version Im using.
From django 1.11 I upgraded to 1.11.13 and it removes the issue. Please do check this as well try to install the django 1.11 instead of 1.11.13. Because the release notes for oscar 1.6 says compatible with django 1.11, 

Please see partial stack trace ;

Request Method: | GET
-- | --
http://localhost:8000/dashboard/catalogue/product-type/create/
1.11
KeyError
u'widget'
/Users/jr/.venv/new_oscar/lib/python2.7/site-packages/django/forms/widgets.py in subwidgets, line 192
/Users/jr/.venv/new_oscar/bin/python
2.7.15
['/Users/jr/projects/django/sample/new_oscar/testshop',  '/Users/jr/.venv/new_oscar/lib/python27.zip',  '/Users/jr/.venv/new_oscar/lib/python2.7',  '/Users/jr/.venv/new_oscar/lib/python2.7/plat-darwin',  '/Users/jr/.venv/new_oscar/lib/python2.7/plat-mac',  '/Users/jr/.venv/new_oscar/lib/python2.7/plat-mac/lib-scriptpackages',  '/Users/jr/.venv/new_oscar/lib/python2.7/lib-tk',  '/Users/jr/.venv/new_oscar/lib/python2.7/lib-old',  '/Users/jr/.venv/new_oscar/lib/python2.7/lib-dynload',  '/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7',  '/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',  '/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',  '/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',  '/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',  '/Users/jr/.venv/new_oscar/lib/python2.7/site-packages']
Mon, 4 Jun 2018 08:18:57 +0000


Thank you

**Comment by solarissmoke** [comment] 2018-06-04 08:31
You should always be using the latest minor version of Django - when an app says it support 1.11 the assumption is you will keep up to date with bug fixes in Django itself.

This looks like an issue in Django, so closing.

**Comment by jackgreen04** [comment] 2018-06-04 08:32
Okay, thank you.

**Closed by solarissmoke** 2018-06-04 08:31 UTC
