### ISSUE TITLE
Not able to access admin dashboard

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [django-oscar/django-oscar#2650] opened 2018-03-13 09:43 UTC
Not receiving an email with the credentials

**Comment by solarissmoke** [comment] 2018-03-13 10:10
Duplicate of #2531

**Closed by solarissmoke** 2018-03-13 10:10 UTC

**Comment by Jeyakumarrathnaselvi** [comment] 2018-03-13 10:33
How to access admin dashboard to validate the features

**Comment by solarissmoke** [comment] 2018-03-13 10:52
Your best bet is to fire up the sandbox locally.
https://django-oscar.readthedocs.io/en/latest/internals/sandbox.html#running-the-sandbox-locally
