### ISSUE TITLE
Only product.primary_image shown in the product page!

### ISSUE THREAD

**Issue by ceyboo** [django-oscar/django-oscar#2726] opened 2018-05-30 14:28 UTC
### Issue Summary

Only product.primary_image shown in the product detail page even if I added multiple images for products. 

all_images=product.get_all_images returns 0 and gallery.html shows the "only one image to show" section. But I added at least 4 images for each product and I can see them at the dashboard product update page.

**Comment by solarissmoke** [comment] 2018-06-01 04:45
I am not able to reproduce this issue - works fine in the sandbox with multiple images. Please can you provide more detailed information/steps to reproduce. In particular:

- Which version of Oscar
- Whether your products are variants
- Any custom templates

**Comment by solarissmoke** [comment] 2018-06-06 02:38
What is the output if you call `get_all_images()` for that product in the shell?

**Comment by ceyboo** [comment] 2018-06-06 10:05
It returns 0. Then in the gallery.html code below, its else condition works and I can see only one image.

```
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

{% with all_images=product.get_all_images %}
    {# use length rather then count as the images get queried anyways #}

    {% if all_images|length > 1 %}

        <div id="product_gallery" class="carousel slide">

            <div class="thumbnail">
                <div class="carousel-inner" role="listbox">
                {% for image in all_images %}
                    <div class="item {% if forloop.first %}active{% endif %}">
                        {% thumbnail image.original "440x400" upscale=False as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                        {% endthumbnail %}
                    </div>
                {% endfor %}
                </div>
                <a class="carousel-control left" href="#product_gallery" role="button" data-slide="prev">
                    <span class="icon-prev fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-angle-left fa-stack-1x"></i>
                    </span>
                </a>
                <a class="carousel-control right" href="#product_gallery" role="button" data-slide="next">
                    <span class="icon-next fa-stack fa-lg" aria-hidden="true">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-angle-right fa-stack-1x"></i>
                    </span>
                </a>
            </div>

            <ol class="carousel-indicators thumbnail">
                {% for image in all_images %}
                    <li data-target="#product_gallery" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}">
                        {% thumbnail image.original "65x55" crop="center" as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                        {% endthumbnail %}
                    </li>
                {% endfor %}
            </ol>
        </div>

    {% else %}

        {# Only one image to show #}
        <div id="product_gallery" class="carousel">
            <div class="thumbnail">
                <div class="carousel-inner">
                    <div class="item active">
                    {% with image=product.primary_image %}
                        {% thumbnail image.original "440x400" upscale=False as thumb %}
                            <!-- <h1>hello {{ all_images|length }}</h1> -->
                            <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
                        {% endthumbnail %}
                    {% endwith %}
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endwith %}


```

**Comment by solarissmoke** [comment] 2018-06-06 10:52
When you say it returns 0, do you mean literally 0 as opposed to an empty queryset? If you mean 0 then you (or something else) must have modified that method because it can only return a queryset.

I'm still not able to reproduce this issue, and it works fine in the sandbox. If you are able to track down where specifically in Oscar the wrong result is arising then we can look into it.

**Comment by ceyboo** [comment] 2018-06-06 11:02
It does not work fine in my example but I just found the problem and fixed it.  

The original **Gallery.html** uses **product.get_all_images**. It does not work. I changed this variable and write  **product.images.all** and then I start to see multiple images in my site. 

```
**WRONG**

{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

{% with all_images=product.get_all_images %}
    {# use length rather then count as the images get queried anyways #}
```

```
**TRUE**

{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

{% with all_images=product.images.all %}
    {# use length rather then count as the images get queried anyways #}
```

**Comment by solarissmoke** [comment] 2018-06-06 11:07
Except that `get_all_images` works just fine in the sandbox - it isn't wrong. 

I am going to close this on the basis that we can't reproduce this in the sandbox, and I can't see how `get_all_images()` would return `0` at all unless you have modified it. If you are able to show us how to replicate the same issue in the sandbox we can look into it again.

**Closed** 2018-06-06 11:07 UTC
