### ISSUE TITLE
Product variation

### ISSUE THREAD

**Issue by Philoow** [django-oscar/django-oscar#1800] opened 2015-07-09 07:42 UTC
Hello,

I have a question about oscar features. Is there product variation ? I mean can a customer select some values (color, size, etc) on the product page and then the price update itself ? 

Thank you

**Comment by john-parton** [comment] 2015-07-22 14:42
Variations are not properly implemented, though there are some workarounds.

Basically, you have to create a "parent" `Product` instance and a "child" `Product` instances for each variation. If you open up the dashboard and try to create a product, you should be able to figure it out relatively easily.

You'll have to rewrite the necessary forms and views to allow your users to select the correct child based on the possible attribute values.

There's an open issue here discussing some of the current problems: https://github.com/django-oscar/django-oscar/issues/675

If you have more specific concerns, they're probably best directed there.

Thanks.

**Comment by solarissmoke** [comment] 2017-04-22 06:14
Closing as a duplicate of #675.

**Closed by solarissmoke** 2017-04-22 06:14 UTC
