### ISSUE TITLE
Error on saving Category, On a New installation

### ISSUE THREAD

**Issue by artndes9** [django-oscar/django-oscar#3733] opened 2021-07-21 18:11 UTC
#### Category reports error on save.

```
OperationalError at /dashboard/catalogue/categories/9/update/
(1093, "Table 'catalogue_category' is specified twice, both as a target for 'UPDATE' and as a separate source for data")
```
Resulting query 
```
(b'UPDATE `catalogue_category` SET `ancestors_are_public` = NOT EXISTS(SELECT U'
 b'0.`id` FROM `catalogue_category` U0 WHERE (U0.`depth` < `catalogue_category`'
 b'.`depth` AND NOT U0.`is_public` AND `catalogue_category`.`path` LIKE BINARY '
 b"CONCAT(REPLACE(REPLACE(REPLACE(U0.`path`, '\\\\', '\\\\\\\\'), '%', '\\%'),"
 b" '_', '\\_'), '%'))) WHERE `catalogue_category`.`id` = 9")
``` 

Server Version:  10.2.26-MariaDB-1:10.2.26

**Comment by solarissmoke** [comment] 2021-07-22 05:15
This looks like a duplicate of #3335 - see the links and discussion there for the underlying problem with MySQL (and MariaDB). Patches to make this work on either database are welcome.

**Closed by solarissmoke** 2021-07-22 05:15 UTC
