### ISSUE TITLE
cryptocurrency

### ISSUE THREAD

**Issue by corsur** [django-oscar/django-oscar#2612] opened 2018-02-10 23:06 UTC
i help run a cryptocurrency business and we are considering creating a cryptocurrency payment solution. if we were to create this, would you consider a pull request?

**Comment by solarissmoke** [comment] 2018-02-11 03:30
Hi! A payment module wouldn't be included as part of Oscar core, but if you do create one then we'd definitely link to it in the [relevant section of the readme](https://github.com/django-oscar/django-oscar#extensions).

**Comment by solarissmoke** [comment] 2018-02-19 05:14
Closing as this is not a bug/feature request. If/when you have a cryptocurrency module please ping us and we'll add a link to it.

**Closed by solarissmoke** 2018-02-19 05:14 UTC
