### ISSUE TITLE
Product Bad Request (400)

### ISSUE THREAD

**Issue by lieuvinhthu** [django-oscar/django-oscar#2912] opened 2019-01-10 07:31 UTC
### Issue Summary
After install, I going to Dashboard > Catalogue > Products 
Bad Request (400)

### Steps to Reproduce
Product page
![image](https://user-images.githubusercontent.com/9067918/50952632-974c4300-14e3-11e9-839e-52d965a0d6dc.png)

 Error in console:  Invalid URL name dashboard:voucher-set-list
![image](https://user-images.githubusercontent.com/9067918/50952875-530d7280-14e4-11e9-9d97-4e05c6103d32.png)

### Technical details

* Python version: Python 3.7.1
* Django version: 2.1.4
* Oscar version:  2.0.dev0

**Comment by solarissmoke** [comment] 2019-01-10 07:55
You appear to be using Windows, which is unlikely to work very well, if at all - there is a [warning about this in the documentation](https://django-oscar.readthedocs.io/en/releases-1.1/internals/sandbox.html#run-the-sandbox-locally). 

Unfortunately you're unlikely to get much help if this is a Windows issue. I can't reproduce it on *NIX, and we don't officially support Windows.

**Comment by solarissmoke** [comment] 2019-01-29 02:46
Closing as this is most likely a file path issue on Windows.

**Closed by solarissmoke** 2019-01-29 02:46 UTC
