### ISSUE TITLE
'str' object has no attribute 'strategy' When Rendering Content Blocks

### ISSUE THREAD

**Issue by artforlife** [django-oscar/django-oscar#2429] opened 2017-07-28 01:55 UTC
I get the following error when attempting to access a page with a Product List content block. When I create the block, I place it onto `/` URL. Then, when I access the main page, I get the error. Are you aware of this, and how can I fix this?

> 
> Request Method: | GET
> -- | --
> http://localhost:8000/
> 1.10.7
> AttributeError
> 'str' object has no attribute 'strategy'
> /Users/userman/www/sites/Playground/Django-tut/django-oscar/django-oscar-env/lib/python3.6/site-packages/oscar/templatetags/purchase_info_tags.py  in purchase_info_for_product, line 13
> /Users/userman/www/sites/Playground/Django-tut/django-oscar/django-oscar-env/bin/python
> 3.6.0

**Comment by solarissmoke** [comment] 2017-07-28 03:14
I can't reproduce this on the sandbox - there's not enought information here to know what could be going on. Please include the full stack trace including the templates that are being used.

**Comment by 40ft** [comment] 2017-07-28 07:36
It's possibly a bug as described here: https://medium.com/@jayakrishnandamodaran/solving-str-object-has-no-attribute-strategy-in-django-oscar-8f38f9dc6606 . It requires a workaround until the next version of oscar is released.

**Comment by solarissmoke** [comment] 2017-07-28 08:12
Thanks @40ft, you're right. This was fixed in #2243 . You can use version `1.5rc2` which has this fix incorporated into it.

**Closed by solarissmoke** 2017-07-28 08:12 UTC
