### ISSUE TITLE
category images not showing

### ISSUE THREAD

**Issue by Nuruddinjr** [django-oscar/django-oscar#2060] opened 2016-06-27 11:28 UTC
```python
{% category_tree depth=2 as tree_categories %}
{% for category, info in tree_categories %}
    {% if info.level == 0 %}
        <li>
            {% if info.has_children %}
                . . .
    {% category_tree depth=1 parent=category as sub_categories %}
    {% for sub_category, info in sub_categories %}
    <div class="col-md-4">
        <a href="{{ sub_category.get_absolute_url }}">
            <h5 class="dropdown-menu-category-title">
                {#here only the first category is shown with image, the rest is without image#}
                {% thumbnail sub_category.image "100x100" upscale=False as thumb %}
                    <img
                            src="{{ thumb.url }}"
                            alt="{{ sub_category.name }}"
                            title="{{ sub_category.name }}"
                    />
                {% endthumbnail %}
                {{ sub_category.name }}

            </h5>
        </a>
            <ul class="dropdown-menu-category-list">
                {% category_tree depth=1 parent=sub_category as sub_sub_categories %}
                {% for ss_category, info in sub_sub_categories %}
                    <li>
                        <a href="{{ ss_category.get_absolute_url }}">{{ ss_category.name }}</a>
                        <p>{{ ss_category.description|safe }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
                ...
                {% if info.level == 0 %}   {# Here image is shown  #}
                    {% thumbnail category.image "300x300" upscale=False as thumb %}
                        <img class="dropdown-menu-category-section-theme-img"
                             src="{{ thumb.url }}"
                             alt="{{ category.name }}" title="{{ category.name }}"
                             style="right: 10px;"/>
                    {% endthumbnail %}
                {% endif %}
                </div>
                </div>
            {% endif %}
        </li>

    {% endif %}
{% endfor %}

**Comment by sasha0** [comment] 2016-06-28 21:07
Closing as duplicate of #2059.

**Closed by sasha0** 2016-06-28 21:07 UTC
