### ISSUE TITLE
Price ranges for parent products

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1648] opened 2015-01-27 19:57 UTC
The default strategy classes in `partner.strategy` as well as the default templates don't allow parents to express their price as a range.

It would be nice to be able to do something like this with minimal configuration:

![screenshot from 2015-01-27 13 45 57](https://cloud.githubusercontent.com/assets/2071543/5925691/0b81555c-a62b-11e4-83c2-c0580d4028ed.png)

Likewise, the price range would show on the product page.

I'm working on a fix.

Possibly related: https://github.com/django-oscar/django-oscar/issues/675

**Comment by john-parton** [comment] 2015-04-01 20:45
I think this might be a duplicate of https://github.com/django-oscar/django-oscar/issues/1085

**Comment by sasha0** [comment] 2018-02-21 10:31
Closing as a duplicate of #1085.

**Closed by sasha0** 2018-02-21 10:31 UTC
